services:
  rompetomp_inertia.inertia:
    class: Rompetomp\InertiaBundle\Service\Inertia

  Rompetomp\InertiaBundle\Service\InertiaInterface: '@rompetomp_inertia.inertia'

  rompetomp_inertia.gateway:
    class: Rompetomp\InertiaBundle\Ssr\HttpGateway
    arguments:
      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
      $inertia: '@rompetomp_inertia.inertia'

  Rompetomp\InertiaBundle\Ssr\GatewayInterface: '@rompetomp_inertia.gateway'

  rompetomp_inertia.twig_extension:
    class: Rompetomp\InertiaBundle\Twig\InertiaExtension
    public: false
    arguments:
      $inertia: '@rompetomp_inertia.inertia'
      $gateway: '@rompetomp_inertia.gateway'
    tags:
      - { name: twig.extension }

  Rompetomp\InertiaBundle\EventListener\InertiaListener:
    arguments:
      $inertia: '@rompetomp_inertia.inertia'
      $debug: '%kernel.debug%'
